fix: Package version, CI - Corrected version number in docs and package - disabled coveralls - fix tox not running selected env only - Parallel runner support for coveralls
TODO:
- Split github action

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -52,12 +52,21 @@ jobs:
     - name: Install Dependencies
       run: uv sync --only-group test
     - name: Run test suite
-      run: uv run tox run-parallel -e "$(tox -a | grep py$(echo "${{ matrix.python-version }}" | tr -d . ))" -- "--cov=mongoengine"
-    - name: Send coverage to Coveralls
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        COVERALLS_SERVICE_NAME: github
-      run: coveralls
+      run: |
+        envs="$(uv run tox -a | grep py$(echo "${{ matrix.python-version }}" | tr -d . ) || true)"
+        if [ -z "$envs" ]; then
+          echo "Error: No matching tox envs found" >&2
+          exit 1
+        fi
+        echo "Running with: $envs"
+        uv run tox run-parallel -e "$envs" -- "--cov=mongoengine --cov-report="
+        uv run coverage combine
+        uv run coverage report
+#    - name: Send coverage to Coveralls
+#      env:
+#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        COVERALLS_SERVICE_NAME: github
+#      run: uv run coveralls
 
   build_doc_dryrun:
     # ensures that readthedocs can be built continuously
